version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: cassandra:3.11
        environment:
          MAX_HEAP_SIZE: 1024M
          HEAP_NEWSIZE: 100M
    steps:
      - checkout
      - run:
          name: Start CassandraDB
          command: dockerize -wait tcp://localhost:9042 -timeout 1m
      - run:
          name: Install cqlsh via pip3
          command: |
            sudo apt install python-pip
            sudo pip install cqlsh
            cqlsh --version
            touch a.cql
            cqlsh --cqlversion=3.4.4 -f a.cql

workflows:
  test:
    jobs:
      - build
