version: 2.1
jobs:
  buil:
    docker:
      - image: circleci/node:8.9.4
      - image: rabbitmq:latest
    steps:
      - checkout
  integration-test:
    docker:
      - image: circleci/node:8.9.4
      - image: cassandra:3.11
    steps:
      - checkout
      - run:
          name: Start CassandraDB
          command: dockerize -wait tcp://localhost:9042 -timeout 1m

workflows:
  test:
    jobs:
      - build
