version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: cassandra:3.11
        environment:
          MAX_HEAP_SIZE: 1024M
          HEAP_NEWSIZE: 100M
    steps:
      - checkout
      - run:
          name: Start CassandraDB
          command: dockerize -wait tcp://localhost:9042 -timeout 1m
      - run:
          name: Install cqlsh via pip
          command: |
            sudo apt install python3-pip
            pip3 install cqlsh==4.1.1
            cqlsh --version

workflows:
  test:
    jobs:
      - build
