version: 2
jobs:
  build:
    working_directory: ~/your-app-name
    docker:
      - image: circleci/ruby:2.4.1
     environment:
       RAILS_ENV: test
  steps:
      - checkout
      
      # Setup the environment
    - run: cp .sample.env .env

      # Run the tests
    - run: bundle exec rake
